create table if not exists public.leaderboard_entries (
  mint text primary key,
  symbol text not null,
  name text,
  image_url text,
  creator_wallet text not null,
  creator_wallet_short text not null,
  creator_username text,
  creator_provider text,
  creator_url text,
  creator_pfp text,
  lifetime_total_sol double precision not null default 0,
  lifetime_earned_sol double precision not null default 0,
  claimable_sol double precision not null default 0,
  royalty_bps integer not null default 0,
  royalty_pct double precision not null default 0,
  is_graduated integer not null default 1,
  bags_url text,
  discovery_source text,
  volume_24h_usd double precision not null default 0,
  volume_1h_usd double precision not null default 0,
  volume_6h_usd double precision not null default 0,
  volume_7d_usd double precision not null default 0,
  trade_count_1h integer not null default 0,
  trade_count_6h integer not null default 0,
  trade_count_24h integer not null default 0,
  trade_count_7d integer not null default 0,
  launch_created_at text,
  rank_score double precision not null default 0,
  momentum_score double precision not null default 0,
  ai_readiness_score double precision not null default 0,
  last_trade_at text,
  source text not null default 'bitquery',
  synced_at text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.token_ai_features (
  mint text primary key references public.leaderboard_entries(mint) on delete cascade,
  age_hours double precision not null default 0,
  volume_growth_1h_vs_24h double precision not null default 0,
  volume_growth_24h_vs_7d double precision not null default 0,
  trade_velocity_1h double precision not null default 0,
  revenue_velocity_sol double precision not null default 0,
  has_metadata_image integer not null default 0,
  has_social_creator integer not null default 0,
  low_liquidity_risk integer not null default 0,
  high_momentum integer not null default 0,
  ai_summary_input_json text not null,
  rank_reason text,
  growth_reason text,
  risk_reason text,
  recommended_action text,
  updated_at text not null
);

create table if not exists public.token_ai_recommendations (
  mint text primary key references public.leaderboard_entries(mint) on delete cascade,
  symbol text not null,
  recommendation_type text not null,
  stance text not null,
  confidence text not null,
  title text not null,
  insight text not null,
  action text not null,
  evidence_json text not null,
  model_provider text,
  model_name text,
  generated_at text not null,
  source_snapshot_at text not null
);

create table if not exists public.leaderboard_sync_runs (
  id bigint generated by default as identity primary key,
  status text not null,
  source text not null,
  message text,
  tokens_seen integer not null default 0,
  synced_entries integer not null default 0,
  created_at text not null default now()::text
);

create table if not exists public.app_state (
  key text primary key,
  value text,
  updated_at text not null default now()::text
);

create index if not exists leaderboard_entries_rank_score_idx on public.leaderboard_entries (rank_score desc);
create index if not exists leaderboard_entries_symbol_idx on public.leaderboard_entries (symbol);
create index if not exists leaderboard_entries_creator_wallet_idx on public.leaderboard_entries (creator_wallet);
create index if not exists leaderboard_sync_runs_created_at_idx on public.leaderboard_sync_runs (created_at desc);
